baseURL = "https://topeschool-commits.github.io/testing-site/"
languageCode = "en-us"
title = "Testing Site"

[params]
  description = "New Empire Testing Site"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Category 1"
    url = "/categories/category-1/"
    weight = 2
  [[menu.main]]
    name = "Category 2"
    url = "/categories/category-2/"
    weight = 3
